language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"

notifications:
  email:
    recipients:
      - m.anangnur@gmail.com
      on_success: change
      on_failure: always
